version: '2.1'

services:
    one_container:
        build:
            context: .
            dockerfile: Dockerfile_one_container
            args:
                PHP_VERSION: "${PHP_VERSION:-8.1}"
                ELASTIC_APM_PHP_AGENT_INSTALL_LOCAL_EXTENSION_BINARY: "${ELASTIC_APM_PHP_AGENT_INSTALL_LOCAL_EXTENSION_BINARY:-}"
                ELASTIC_APM_PHP_AGENT_INSTALL_PACKAGE_FROM_URL: "${ELASTIC_APM_PHP_AGENT_INSTALL_PACKAGE_FROM_URL:-}"
                ELASTIC_APM_PHP_AGENT_INSTALL_RELEASE_VERSION: "${ELASTIC_APM_PHP_AGENT_INSTALL_RELEASE_VERSION:-}"
        volumes:
            - ./:/FROM_HOST
            - ./:/var/www/html
        environment:
            ELASTIC_APM_SERVER_URL: apm-server:8200
        ports:
            - "${ADDRESS_ON_HOST_TO_BIND_APP_HTTP:-127.0.0.1}:${ONE_CONTAINER_PORT_ON_HOST_TO_BIND_APP_HTTP:-8081}:80"
        depends_on:
            apm-server:
                condition: service_healthy

    two_containers_frontend:
        image: httpd
        depends_on:
            - two_containers_backend
        volumes:
            - ./apache_httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
            - ./apache_httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf:ro
        ports:
            - "${ADDRESS_ON_HOST_TO_BIND_APP_HTTP:-127.0.0.1}:${TWO_CONTAINERS_PORT_ON_HOST_TO_BIND_APP_HTTP:-8082}:80"

    two_containers_backend:
        build:
            context: .
            dockerfile: Dockerfile_two_containers_backend
            args:
                PHP_VERSION: "${PHP_VERSION:-8.1}"
                ELASTIC_APM_PHP_AGENT_INSTALL_LOCAL_EXTENSION_BINARY: "${ELASTIC_APM_PHP_AGENT_INSTALL_LOCAL_EXTENSION_BINARY:-}"
                ELASTIC_APM_PHP_AGENT_INSTALL_PACKAGE_FROM_URL: "${ELASTIC_APM_PHP_AGENT_INSTALL_PACKAGE_FROM_URL:-}"
                ELASTIC_APM_PHP_AGENT_INSTALL_RELEASE_VERSION: "${ELASTIC_APM_PHP_AGENT_INSTALL_RELEASE_VERSION:-}"
        volumes:
            - ./:/FROM_HOST
            - ./:/var/www/html
        environment:
            ELASTIC_APM_SERVER_URL: apm-server:8200
        depends_on:
            apm-server:
                condition: service_healthy

    elasticsearch:
        container_name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION:-7.17.1}
        environment:
            - cluster.name=docker-cluster
            - xpack.security.enabled=false
            - bootstrap.memory_lock=true
            - network.host=0.0.0.0
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
            - "path.data=/usr/share/elasticsearch/data/${STACK_VERSION:-7.17.1}"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        mem_limit: 2g
        logging:
            driver: 'json-file'
            options:
                max-size: '2m'
                max-file: '5'
        ports:
            - "${ELASTICSEARCH_HOST:-127.0.0.1}:${ELASTICSEARCH_PORT:-9200}:9200"
        healthcheck:
            test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -vq '\"status\":\"red\"'"]
            retries: 10
            interval: 20s

    kibana:
        container_name: kibana
        image: docker.elastic.co/kibana/kibana:${STACK_VERSION:-7.17.1}
        environment:
            SERVER_NAME: kibana.example.org
            ELASTICSEARCH_URL: http://elasticsearch:9200
        ports:
            - "${KIBANA_HOST:-127.0.0.1}:${KIBANA_PORT:-5601}:5601"
        logging:
            driver: 'json-file'
            options:
                max-size: '2m'
                max-file: '5'
        healthcheck:
            test: ["CMD", "curl", "--write-out", "'HTTP %{http_code}'", "--silent", "--output", "/dev/null", "http://kibana:5601/"]
            retries: 10
            interval: 10s
        depends_on:
            elasticsearch:
                condition: service_healthy

    apm-server:
        container_name: apm-server
        image: docker.elastic.co/apm/apm-server:${STACK_VERSION:-7.17.1}
        ports:
            - "${APM_SERVER_HOST:-127.0.0.1}:${APM_SERVER_PORT:-8200}:8200"
            - "${APM_SERVER_HOST:-127.0.0.1}:${APM_SERVER_MONITOR_PORT:-6060}:6060"
        command: >
            apm-server -e
              -E apm-server.frontend.enabled=true
              -E apm-server.frontend.rate_limit=100000
              -E apm-server.host=0.0.0.0:8200
              -E apm-server.read_timeout=1m
              -E apm-server.shutdown_timeout=2m
              -E apm-server.write_timeout=1m
              -E apm-server.rum.enabled=true
              -E setup.kibana.host=kibana:5601
              -E setup.template.settings.index.number_of_replicas=0
              -E xpack.monitoring.elasticsearch=true
              -E output.elasticsearch.enabled=${APM_SERVER_ELASTICSEARCH_OUTPUT_ENABLED:-true}
              -E apm-server.kibana.enabled=true
              -E apm-server.kibana.host=kibana:5601
              -E logging.level=debug
              -E logging.to_files=true
              -E logging.files.path=/var/log/APM_Server
              -E logging.files.name=log.txt
        cap_drop:
            - ALL
        cap_add:
            - CHOWN
            - DAC_OVERRIDE
            - SETGID
            - SETUID
        logging:
            driver: 'json-file'
            options:
                max-size: '2m'
                max-file: '5'
        depends_on:
            elasticsearch:
                condition: service_healthy
            kibana:
                condition: service_healthy
        healthcheck:
            test: ["CMD", "curl", "--write-out", "'HTTP %{http_code}'", "--silent", "--output", "/dev/null", "http://apm-server:8200/"]
            retries: 10
            interval: 10s
